# Generated by Django 5.2.3 on 2025-06-30 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_tags', to='logbook.entry')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_tags', to='logbook.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ProgrammerMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievedAt', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ahcievements', to='logbook.milestone')),
                ('programmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='logbook.programmer')),
            ],
        ),
    ]
